language: cpp
matrix:
  include:
  - os: linux
    env: CONFIG=Debug
    compiler: gcc
  - os: linux
    env: CONFIG=Release
    compiler: gcc
  - os: linux
    env: CONFIG=Debug
    compiler: clang
  - os: linux
    env: CONFIG=Release
    compiler: clang
  - os: osx
    env: CONFIG=Debug
    compiler: gcc
  - os: osx
    env: CONFIG=Release
    compiler: gcc
  - os: osx
    env: CONFIG=Debug
    compiler: clang
  - os: osx
    env: CONFIG=Release
    compiler: clang
sudo: false
dist: trusty
before_install:
  - if [ "$TRAVIS_OS_NAME" == linux ] ; then sudo apt-get install -y xorg-dev ; fi
  - if [ "$CONFIG" == "Debug" ] && [ "$CXX" == "g++" ] && [ "$TRAVIS_OS_NAME" == linux ] ; then pip install --user cpp-coveralls ; fi
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} ..
script:
  - make
  - make test
after_success:
  - if [ "$CONFIG" == "Debug" ] && [ "$CXX" == "g++" ] && [ "$TRAVIS_OS_NAME" == linux ] ; then coveralls --gcov-options '\-lp' --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" ; fi
